/**
 * Created by Ngoc Son Tran on 10/13/2017.
 */
var Constants = {
    ACTION_VOTE_UP: 'ACTION_VOTE_UP',
    ACTION_VOTE_DOWN: 'ACTION_VOTE_DOWN',
    ACTION_VOTE_RESET: 'ACTION_VOTE_RESET',
    ACTION_ADD_STUDENT: 'ACTION_ADD_STUDENT',
    ACTION_REMOVE_STUDENT: 'ACTION_REMOVE_STUDENT',
    ACTION_ADD_TO_CART: 'ACTION_ADD_TO_CART',
    ACTION_REMOVE_FROM_CART: 'ACTION_REMOVE_FROM_CART'
};

module.exports = Constants;